import { json, readJson } from '../lib/http.js';
import { getSupabase } from '../lib/supabase.js';
import { authenticate, generateToken, requireRole } from '../lib/auth.js';
import { generateApiKey, generateRandomPassword, hashPassword } from '../lib/crypto.js';
import { validUsername, validPrefix, int } from '../lib/validate.js';

async function admin(request,env){const a=await authenticate(request,env);if(a.error)return {error:a.error};if(!requireRole(a.user,['admin']))return {error:json({error:'Admin access required'},403)};return a;}

export async function listResellers(request,env){const a=await admin(request,env);if(a.error)return a.error;const s=getSupabase(env);const {data,error}=await s.from('users').select('id,username,role,credits,unlimited,unlimited_expires_at,api_allowed,api_key,prefix,status,created_at').eq('role','reseller').order('created_at',{ascending:false});if(error)return json({error:error.message},500);const names=(data||[]).map(x=>x.username);let counts={};if(names.length){const {data:ks}=await s.from('keys').select('created_by').in('created_by',names);for(const k of ks||[])counts[k.created_by]=(counts[k.created_by]||0)+1;}return json((data||[]).map(x=>({...x,name:x.username,total_keys:counts[x.username]||0})))}

export async function createReseller(request,env){const a=await admin(request,env);if(a.error)return a.error;const b=await readJson(request);const name=String(b.name||'');if(!validUsername(name))return json({error:'Invalid name (2-32 chars, letters/numbers/_)'},400);const s=getSupabase(env);const {data:existing}=await s.from('users').select('id').eq('username',name).maybeSingle();if(existing)return json({error:'Username already exists'},400);const password=generateRandomPassword(12), apiKey=generateApiKey();const {data,error}=await s.from('users').insert({id:crypto.randomUUID(),username:name,password:hashPassword(password),role:'reseller',api_key:apiKey,status:'active',credits:0,unlimited:false,api_allowed:false}).select('id,username').single();if(error)return json({error:error.message},500);return json({success:true,name:data.username,password,api_key:apiKey});}

export async function topup(request,env){const a=await admin(request,env);if(a.error)return a.error;const b=await readJson(request);const name=String(b.name||'');let added=0;if(b.package){added={nano:200,small:550,medium:1150}[b.package]||0;}else if(b.amount!==undefined){added=Number.parseInt(b.amount,10);if(!Number.isFinite(added)||added<1||added>10000000)return json({error:'Invalid amount'},400);}else return json({error:'Package or amount required'},400);if(!added)return json({error:'Invalid package'},400);const s=getSupabase(env);const {data,error}=await s.rpc('adjust_credits',{p_username:name,p_delta:added});if(error)return json({error:error.message},500);return json({success:true,added,credits:data?.credits});}

export async function upgrade(request,env){const a=await admin(request,env);if(a.error)return a.error;const b=await readJson(request);if(!['1m','lifetime'].includes(b.duration))return json({error:'Invalid duration'},400);const expires=b.duration==='1m'?Date.now()+30*86400000:null;const s=getSupabase(env);const {error}=await s.from('users').update({unlimited:true,unlimited_expires_at:expires,api_allowed:true}).eq('username',b.name).eq('role','reseller');if(error)return json({error:error.message},500);return json({success:true});}

export async function downgrade(request,env){const a=await admin(request,env);if(a.error)return a.error;const b=await readJson(request);const s=getSupabase(env);const {error}=await s.from('users').update({unlimited:false,unlimited_expires_at:null}).eq('username',b.name).eq('role','reseller');if(error)return json({error:error.message},500);return json({success:true});}

export async function toggleApi(request,env){const a=await admin(request,env);if(a.error)return a.error;const b=await readJson(request);const enabled=!!b.enabled;const s=getSupabase(env);const {error}=await s.from('users').update({api_allowed:enabled}).eq('username',b.name).eq('role','reseller');if(error)return json({error:error.message},500);return json({success:true,api_allowed:enabled});}

export async function toggleStatus(request,env){const a=await admin(request,env);if(a.error)return a.error;const b=await readJson(request);const status=b.action==='ban'?'banned':'active';const s=getSupabase(env);const {error}=await s.from('users').update({status}).eq('username',b.name).eq('role','reseller');if(error)return json({error:error.message},500);return json({success:true,status});}

export async function loginAs(request,env){const a=await admin(request,env);if(a.error)return a.error;const b=await readJson(request);const s=getSupabase(env);const {data:user,error}=await s.from('users').select('*').eq('username',b.name).eq('role','reseller').eq('status','active').single();if(error||!user)return json({error:'Reseller not found'},404);const token=await generateToken(user,env,{impersonated_by:a.user.id});return json({token});}

export async function deleteReseller(request,env){const a=await admin(request,env);if(a.error)return a.error;const b=await readJson(request);const s=getSupabase(env);const {error}=await s.rpc('delete_reseller',{p_username:b.name});if(error)return json({error:error.message},500);return json({success:true});}

export async function setPrefix(request,env){const a=await authenticate(request,env);if(a.error)return a.error;if(!requireRole(a.user,['admin','reseller']))return json({error:'Reseller access required'},403);const b=await readJson(request);if(!validPrefix(b.prefix))return json({error:'Prefix must be 2-15 alphanumeric characters'},400);const s=getSupabase(env);const {error}=await s.from('users').update({prefix:b.prefix||null}).eq('id',a.user.id);if(error)return json({error:error.message},500);return json({success:true,prefix:b.prefix||null});}

export async function regenApiKey(request,env){const a=await authenticate(request,env);if(a.error)return a.error;if(!requireRole(a.user,['admin','reseller']))return json({error:'Reseller access required'},403);const apiKey=generateApiKey();const s=getSupabase(env);const {error}=await s.from('users').update({api_key:apiKey}).eq('id',a.user.id);if(error)return json({error:error.message},500);return json({success:true,api_key:apiKey});}
